services:
  server:
    build: .
    container_name: bd-server
    networks:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: bd-mongo
    volumes:
      - ./db:/data/db
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
networks:
  db:
